[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Kyle Willmon <kylewillmon@gmail.com>"]
edition = "2018"

[dependencies]

aoclib = { path = "../aoclib" }
clap = "2.33.3"
itertools = "0.9"
thiserror = "1.0.22"
displaydoc = "0.1.7"