[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Kyle Willmon <kylewillmon@gmail.com>"]
edition = "2018"

[dependencies]

aoclib = { path = "../aoclib" }
anyhow = "1.0.35"
clap = "2.33.3"
itertools = "0.9.0"
